// <auto-generated />
namespace InventoryManagement.Migrations.Inventory
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updattingregexandassiginingintitialpreviousvalueas0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updattingregexandassiginingintitialpreviousvalueas0));
        
        string IMigrationMetadata.Id
        {
            get { return "201803310938165_updatting regex and assigining intitial previous value as 0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
