// <auto-generated />
namespace InventoryManagement.Migrations.Inventory
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class defaultvaluetrueforbooleancheck : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(defaultvaluetrueforbooleancheck));
        
        string IMigrationMetadata.Id
        {
            get { return "201803310802535_default value true for boolean check"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
