// <auto-generated />
namespace InventoryManagement.Migrations.Inventory
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class previousValuechangedtoStringforreportpage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(previousValuechangedtoStringforreportpage));
        
        string IMigrationMetadata.Id
        {
            get { return "201804030542038_previousValue changed to String for report page"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
