// <auto-generated />
namespace InventoryManagement.Migrations.Inventory
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testinnngggg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testinnngggg));
        
        string IMigrationMetadata.Id
        {
            get { return "201804062214254_testinnngggg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
